export const HOTELS = [
  {
    id: 1,
    name: "AI Hotel Lansdowne",
    slug: "lansdowne",
    location: "Lansdowne, Uttarakhand",
    description: "Nestled in the serene hills of Lansdowne, experience luxury amidst nature's tranquility.",
    status: "active" as const,
    heroImage: "/images/hero-ai-hotel.jpg",
    rooms: 45,
    established: 2024,
  },
  {
    id: 2,
    name: "AI Hotel Gurugram",
    slug: "gurugram",
    location: "Gurugram, Haryana",
    description: "Modern luxury in the heart of India's millennium city, perfect for business and leisure.",
    status: "coming-soon" as const,
    heroImage: "/images/luxury-suite.jpg",
    rooms: 120,
    established: 2025,
  },
  {
    id: 3,
    name: "AI Hotel Haridwar",
    slug: "haridwar",
    location: "Haridwar, Uttarakhand",
    description: "Spiritual luxury on the banks of the holy Ganges, where tradition meets modern comfort.",
    status: "coming-soon" as const,
    heroImage: "/images/presidential-suite.jpg",
    rooms: 80,
    established: 2025,
  },
  {
    id: 4,
    name: "AI Hotel Rishikesh",
    slug: "rishikesh",
    location: "Rishikesh, Uttarakhand",
    description: "Yoga capital retreat with luxury amenities and breathtaking Himalayan views.",
    status: "coming-soon" as const,
    heroImage: "/images/deluxe-room.jpg",
    rooms: 60,
    established: 2025,
  },
  {
    id: 5,
    name: "AI Hotel Udaipur",
    slug: "udaipur",
    location: "Udaipur, Rajasthan",
    description: "Royal heritage luxury in the City of Lakes, where every moment feels like a fairy tale.",
    status: "coming-soon" as const,
    heroImage: "/images/spa.jpg",
    rooms: 95,
    established: 2025,
  },
  {
    id: 6,
    name: "AI Hotel Jim Corbett",
    slug: "jim-corbett",
    location: "Jim Corbett, Uttarakhand",
    description: "Wildlife luxury resort offering safari adventures and premium forest experiences.",
    status: "coming-soon" as const,
    heroImage: "/images/restaurant.jpg",
    rooms: 40,
    established: 2025,
  },
  {
    id: 7,
    name: "AI Hotel Ayodhya",
    slug: "ayodhya",
    location: "Ayodhya, Uttar Pradesh",
    description: "Spiritual luxury in the holy city, combining devotion with world-class hospitality.",
    status: "coming-soon" as const,
    heroImage: "/images/pool.jpg",
    rooms: 75,
    established: 2025,
  },
  {
    id: 8,
    name: "AI Hotel Ranikhet",
    slug: "ranikhet",
    location: "Ranikhet, Uttarakhand",
    description: "Mountain luxury retreat with panoramic Himalayan views and pristine natural beauty.",
    status: "coming-soon" as const,
    heroImage: "/images/hero-ai-hotel.jpg",
    rooms: 35,
    established: 2025,
  },
  {
    id: 9,
    name: "AI Hotel Dehradun",
    slug: "dehradun",
    location: "Dehradun, Uttarakhand",
    description: "Gateway to the hills luxury hotel, perfect for both business travelers and nature lovers.",
    status: "coming-soon" as const,
    heroImage: "/images/luxury-suite.jpg",
    rooms: 85,
    established: 2025,
  },
]

export const ROOM_TYPES = [
  {
    id: 1,
    name: "Super Deluxe Room",
    description: "Spacious luxury room with mountain views and premium amenities",
    size: "450 sq ft",
    occupancy: "2 Adults + 1 Child",
    price: "₹8,000",
    image: "/images/luxury-suite.jpg",
    amenities: ["Mountain View", "King Size Bed", "Mini Bar", "Balcony", "Premium Toiletries", "Free WiFi"],
  },
  {
    id: 2,
    name: "Deluxe Room",
    description: "Comfortable room with modern amenities and garden views",
    size: "350 sq ft",
    occupancy: "2 Adults",
    price: "₹6,000",
    image: "/images/deluxe-room.jpg",
    amenities: ["Garden View", "Queen Size Bed", "Work Desk", "Tea/Coffee Maker", "Free WiFi", "Air Conditioning"],
  },
  {
    id: 3,
    name: "Standard Room",
    description: "Cozy room with essential amenities for a comfortable stay",
    size: "280 sq ft",
    occupancy: "2 Adults",
    price: "₹4,000",
    image: "/images/presidential-suite.jpg",
    amenities: ["City View", "Double Bed", "Free WiFi", "Air Conditioning", "Room Service", "Daily Housekeeping"],
  },
]

export const AMENITIES = [
  {
    id: 1,
    name: "Multi-Cuisine Restaurant",
    description: "Fine dining with local and international cuisines",
    icon: "UtensilsCrossed",
    category: "dining",
  },
  {
    id: 2,
    name: "Spa & Wellness Center",
    description: "Rejuvenating treatments and wellness therapies",
    icon: "Sparkles",
    category: "wellness",
  },
  {
    id: 3,
    name: "Adventure Activities",
    description: "Trekking, rock climbing, and outdoor adventures",
    icon: "Mountain",
    category: "activities",
  },
  {
    id: 4,
    name: "Nature Walks",
    description: "Guided walks through pristine mountain trails",
    icon: "TreePine",
    category: "activities",
  },
  {
    id: 5,
    name: "Photography Tours",
    description: "Capture stunning landscapes with expert guides",
    icon: "Camera",
    category: "activities",
  },
  {
    id: 6,
    name: "Conference Hall",
    description: "Modern facilities for business meetings and events",
    icon: "Users",
    category: "business",
  },
  {
    id: 7,
    name: "Free WiFi",
    description: "High-speed internet throughout the property",
    icon: "Wifi",
    category: "connectivity",
  },
  {
    id: 8,
    name: "24/7 Concierge",
    description: "Round-the-clock assistance and local expertise",
    icon: "Clock",
    category: "service",
  },
]

export const TESTIMONIALS = [
  {
    id: 1,
    name: "Priya Sharma",
    location: "Delhi",
    rating: 5,
    comment:
      "Absolutely stunning location with exceptional service. The mountain views from our room were breathtaking!",
    date: "December 2024",
  },
  {
    id: 2,
    name: "Rajesh Kumar",
    location: "Mumbai",
    rating: 5,
    comment:
      "Perfect getaway from city life. The staff was incredibly helpful and the amenities exceeded our expectations.",
    date: "November 2024",
  },
  {
    id: 3,
    name: "Anita Gupta",
    location: "Bangalore",
    rating: 5,
    comment: "A truly luxurious experience in the heart of nature. Will definitely return for our next vacation!",
    date: "October 2024",
  },
]

export const BOOKING_URL = "https://live.ipms247.com/booking/book-rooms-a1360degree"

export const NAVIGATION_ITEMS = [
  {
    label: "Hotels",
    href: "/our-hotels",
    submenu: HOTELS.map((hotel) => ({
      label: hotel.name,
      href: `/${hotel.slug}`,
      description: hotel.location,
      status: hotel.status,
    })),
  },
  {
    label: "Stay",
    href: "/rooms-suites",
    submenu: [
      { label: "Rooms & Suites", href: "/rooms-suites", description: "Luxury accommodations" },
      { label: "Amenities", href: "/amenities", description: "Premium facilities" },
      { label: "Packages", href: "/packages", description: "Special offers" },
    ],
  },
  {
    label: "Experience",
    href: "/experiences",
    submenu: [
      { label: "Dining", href: "/dining", description: "Culinary excellence" },
      { label: "Spa & Wellness", href: "/spa", description: "Rejuvenation services" },
      { label: "Activities", href: "/activities", description: "Local experiences" },
    ],
  },
  {
    label: "Events",
    href: "/weddings-events",
    submenu: [
      { label: "Weddings", href: "/weddings", description: "Dream celebrations" },
      { label: "Corporate Events", href: "/corporate", description: "Business gatherings" },
      { label: "Social Events", href: "/social-events", description: "Special occasions" },
    ],
  },
  {
    label: "Gallery",
    href: "/gallery",
  },
  {
    label: "Contact",
    href: "/contact",
  },
]

export const COMPANY_INFO = {
  name: "AI 360° Hotel",
  tagline: "Redefining Boutique Hospitality",
  phone: "+91 98765 43210",
  email: "reservations@ai360hotel.com",
  address: "Corporate Office, New Delhi, India",
}
